

spring.application.name=LMSANASOL
server.port=8088


spring.datasource.url=jdbc:postgresql://ep-rough-haze-a18iashw-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vWzZQdJ82Ppt
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.default_schema=lmsanasol


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


jwt.secret=mysupersecurejwtsecretkeythatismorethan32characters
jwt.expiration=86400000

bunny.api-key=4d8f03e6-a1b9-4ec3-9e32821bcfc2-f674-415e
bunny.library-id=598517


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarabogati09@gmail.com
spring.mail.password=wqdi euvq noaq uhgp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.cors.allowed-origins=http://localhost:3000,http://localhost:8081


logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.com.anasol.training=DEBUG
